# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from experiments5G.communication.grpc import grpc_pb2 as experiments5G_dot_communication_dot_grpc_dot_grpc__pb2


class LatencyExperimentsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MyCall = channel.unary_unary(
                '/experiments5G.LatencyExperiments/MyCall',
                request_serializer=experiments5G_dot_communication_dot_grpc_dot_grpc__pb2.Request.SerializeToString,
                response_deserializer=experiments5G_dot_communication_dot_grpc_dot_grpc__pb2.Response.FromString,
                )


class LatencyExperimentsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MyCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LatencyExperimentsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MyCall': grpc.unary_unary_rpc_method_handler(
                    servicer.MyCall,
                    request_deserializer=experiments5G_dot_communication_dot_grpc_dot_grpc__pb2.Request.FromString,
                    response_serializer=experiments5G_dot_communication_dot_grpc_dot_grpc__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'experiments5G.LatencyExperiments', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LatencyExperiments(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MyCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/experiments5G.LatencyExperiments/MyCall',
            experiments5G_dot_communication_dot_grpc_dot_grpc__pb2.Request.SerializeToString,
            experiments5G_dot_communication_dot_grpc_dot_grpc__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
